[window]
decorations = "Full"
opacity = 0.9
startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Mononoki Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 18.0
offset = { x = 0, y = 4 }

[general]
import = [
    "~/.config/alacritty/themes/kanagawa_dragon.toml",
]
